version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env.play
    command: pnpm dev
    volumes:
      - .:/src
      - /src/node_modules
